import { useEffect, useMemo, useState } from "react";
import {
  X,
  Plus,
  Trash2,
  ChevronLeft,
  ChevronRight,
  Sparkles,
  ImageIcon,
  Package,
  CheckCircle2,
} from "lucide-react";
import { useProducts } from "./auth/ProductsProvider";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogClose,
} from "./ui/dialog";

const BRAND = "#948179";

const uid = () => `${Date.now()}_${Math.random().toString(16).slice(2)}`;
const toNumber = (v, fallback = 0) => {
  const n = Number(v);
  return Number.isFinite(n) ? n : fallback;
};

const categoryPrefix = (category = "") => {
  const c = category.toLowerCase();
  if (c.includes("care")) return "CP";
  if (c.includes("package")) return "PK";
  if (c.includes("add")) return "AO";
  if (c.includes("protect")) return "PR";
  return "PRD";
};

// ✅ autogenerated sku

function Field({ label, hint, children }) {
  return (
    <div className="space-y-1.5">
      <div className="flex items-end justify-between gap-3">
        <label className="text-xs tracking-[0.14em] uppercase text-slate-500">
          {label}
        </label>
        {hint ? <span className="text-xs text-slate-400">{hint}</span> : null}
      </div>
      {children}
    </div>
  );
}

function SegmentedSteps({ steps, current, onGo }) {
  return (
    <div className="flex flex-wrap gap-2">
      {steps.map((s, idx) => {
        const active = idx === current;
        const done = idx < current;

        return (
          <button
            key={s.key}
            type="button"
            onClick={() => onGo(idx)}
            className={[
              "px-3 py-2 rounded-sm border text-xs font-semibold transition flex items-center gap-2",
              active
                ? "bg-white text-slate-900"
                : "bg-white text-slate-600 hover:text-slate-900",
            ].join(" ")}
            style={{
              borderColor: active ? `${BRAND}66` : `${BRAND}22`,
              boxShadow: active ? `0 0 0 1px ${BRAND}33 inset` : "none",
            }}
          >
            {done ? (
              <CheckCircle2 className="w-4 h-4" style={{ color: BRAND }} />
            ) : (
              s.icon
            )}
            <span className="tracking-[0.1em] uppercase">{s.label}</span>
          </button>
        );
      })}
    </div>
  );
}

/** ---------- Variants (product) ---------- **/
function VariantsEditor({ value = [], onChange }) {
  const addVariant = () =>
    onChange([...value, { id: uid(), name: "", price: 0, stock: 0 }]);
  const update = (id, patch) =>
    onChange(value.map((v) => (v.id === id ? { ...v, ...patch } : v)));
  const remove = (id) => onChange(value.filter((v) => v.id !== id));
  const addMaterialPresets = () => {
    const presets = ["Rose Gold", "Gold", "Silver", "Diamond"].map((name) => ({
      id: uid(),
      name,
      price: 0,
      stock: 0,
    }));

    // ✅ avoid duplicates by name
    const existingNames = new Set(
      (value || []).map((v) => (v.name || "").toLowerCase()),
    );
    const next = [
      ...(value || []),
      ...presets.filter((p) => !existingNames.has(p.name.toLowerCase())),
    ];

    onChange(next);
  };

  return (
    <div
      className="rounded-md border bg-white p-4 space-y-3"
      style={{ borderColor: `${BRAND}26` }}
    >
      <div className="flex items-center gap-2">
        <button
          type="button"
          onClick={addMaterialPresets}
          className="inline-flex items-center gap-2 text-xs font-semibold px-3 py-2 rounded-sm border bg-white hover:bg-slate-50"
          style={{ borderColor: `${BRAND}26` }}
        >
          Add Materials
        </button>

        <button
          type="button"
          onClick={addVariant}
          className="inline-flex items-center gap-2 text-xs font-semibold px-3 py-2 rounded-sm text-white hover:opacity-90"
          style={{ backgroundColor: BRAND }}
        >
          <Plus className="w-4 h-4" />
          Add Variant
        </button>
      </div>

      <div className="space-y-3">
        {value.map((variant) => (
          <div
            key={variant.id}
            className="border rounded-md p-3 bg-white"
            style={{ borderColor: `${BRAND}1f` }}
          >
            <div className="grid sm:grid-cols-4 gap-3 items-start">
              {/* NAME */}
              <div className="space-y-1">
                <label className="text-xs font-semibold text-slate-600">
                  Material
                </label>
                <input
                  value={variant.name}
                  onChange={(e) => update(variant.id, { name: e.target.value })}
                  placeholder="Gold"
                  className="w-full border rounded-sm px-3 py-2 bg-white"
                  style={{ borderColor: `${BRAND}26` }}
                />
              </div>

              {/* DESCRIPTION (span 2 columns) */}
              <div className="space-y-1 sm:col-span-2">
                <label className="text-xs font-semibold text-slate-600">
                  Description
                </label>
                <input
                  value={variant.description || ""}
                  onChange={(e) =>
                    update(variant.id, { description: e.target.value })
                  }
                  placeholder="18k solid gold"
                  className="w-full border rounded-sm px-3 py-2 bg-white"
                  style={{ borderColor: `${BRAND}26` }}
                />
              </div>

              {/* PRICE + STOCK */}
              <div className="space-y-2">
                <div className="space-y-1">
                  <label className="text-xs font-semibold text-slate-600">
                    Price
                  </label>
                  <input
                    type="number"
                    value={variant.price}
                    onChange={(e) =>
                      update(variant.id, { price: e.target.value })
                    }
                    placeholder="₦"
                    className="w-full border rounded-sm px-3 py-2 bg-white"
                    style={{ borderColor: `${BRAND}26` }}
                  />
                </div>

                <div className="space-y-1">
                  <label className="text-xs font-semibold text-slate-600">
                    Stock
                  </label>
                  <div className="flex gap-2">
                    <input
                      type="number"
                      value={variant.stock}
                      onChange={(e) =>
                        update(variant.id, { stock: e.target.value })
                      }
                      placeholder="Qty"
                      className="w-full border rounded-sm px-3 py-2 bg-white"
                      style={{ borderColor: `${BRAND}26` }}
                    />
                    <button
                      type="button"
                      onClick={() => remove(variant.id)}
                      className="w-10 h-10 rounded-sm border bg-white flex items-center justify-center hover:bg-slate-50"
                      style={{ borderColor: `${BRAND}26` }}
                      aria-label="Remove variant"
                    >
                      <Trash2 className="w-4 h-4 text-rose-500" />
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        ))}

        {value.length === 0 && (
          <p className="text-sm text-slate-500">No variants yet.</p>
        )}
      </div>
    </div>
  );
}

/** ---------- Extras (with variants shown under each extra) ---------- **/
function ExtrasEditor({ value = [], onChange }) {
  const addExtra = () => {
    onChange([
      ...value,
      {
        id: uid(),
        name: "",
        price: 0,
        type: "toggle",
        promptTitle: "Your reply",
        promptPlaceholder: "Type here...",
        requiredText: false,
        description: "",

        stock: "",
        active: true,
        variants: [],
      },
    ]);
  };

  const update = (id, patch) =>
    onChange(value.map((x) => (x.id === id ? { ...x, ...patch } : x)));

  const remove = (id) => onChange(value.filter((x) => x.id !== id));

  const addExtraVariant = (extraId) => {
    const extra = value.find((x) => x.id === extraId);
    const next = [
      ...(extra?.variants || []),
      { id: uid(), name: "", price: 0, stock: 0 },
    ];
    update(extraId, { variants: next });
  };

  const updateExtraVariant = (extraId, variantId, patch) => {
    const extra = value.find((x) => x.id === extraId);
    const next = (extra?.variants || []).map((v) =>
      v.id === variantId ? { ...v, ...patch } : v,
    );
    update(extraId, { variants: next });
  };

  const removeExtraVariant = (extraId, variantId) => {
    const extra = value.find((x) => x.id === extraId);
    const next = (extra?.variants || []).filter((v) => v.id !== variantId);
    update(extraId, { variants: next });
  };

  return (
    <div
      className="rounded-md border bg-white p-4 space-y-3"
      style={{ borderColor: `${BRAND}26` }}
    >
      <div className="flex items-center justify-between gap-3">
        <div>
          <p className="font-semibold text-slate-900">Extras (Add-ons)</p>
          <p className="text-xs text-slate-500">
            Each extra can have its own variants (Basic/Premium).
          </p>
        </div>
        <button
          type="button"
          onClick={addExtra}
          className="inline-flex items-center gap-2 text-xs font-semibold px-3 py-2 rounded-sm text-white hover:opacity-90"
          style={{ backgroundColor: BRAND }}
        >
          <Plus className="w-4 h-4" />
          Add Extra
        </button>
      </div>

      <div className="space-y-3">
        {value.map((extra) => (
          <div
            key={extra.id}
            className="border rounded-md p-4 bg-white space-y-4"
            style={{ borderColor: `${BRAND}1f` }}
          >
            <div className="flex items-start justify-between gap-3">
              <div className="grid sm:grid-cols-2 gap-4 flex-1">
                <Field label="Extra name">
                  <input
                    value={extra.name}
                    onChange={(e) => update(extra.id, { name: e.target.value })}
                    className="w-full border rounded-sm px-3 py-2 bg-white"
                    style={{ borderColor: `${BRAND}26` }}
                    placeholder="Gift wrap"
                  />
                </Field>

                <Field label="Base price (NGN)" hint="Optional">
                  <input
                    type="number"
                    value={extra.price}
                    onChange={(e) =>
                      update(extra.id, { price: e.target.value })
                    }
                    className="w-full border rounded-sm px-3 py-2 bg-white"
                    style={{ borderColor: `${BRAND}26` }}
                    placeholder="1500"
                  />
                </Field>

                <Field label="Type">
                  <select
                    value={extra.type || "toggle"}
                    onChange={(e) => update(extra.id, { type: e.target.value })}
                    className="w-full border rounded-sm px-3 py-2 bg-white"
                    style={{ borderColor: `${BRAND}26` }}
                  >
                    <option value="toggle">Toggle (select)</option>
                    <option value="text">Text (user types)</option>
                  </select>
                </Field>

                <Field label="Stock (optional)">
                  <input
                    value={extra.stock}
                    onChange={(e) =>
                      update(extra.id, { stock: e.target.value })
                    }
                    className="w-full border rounded-sm px-3 py-2 bg-white"
                    style={{ borderColor: `${BRAND}26` }}
                    placeholder="Leave empty if unlimited"
                  />
                </Field>

                <Field label="Description (optional)">
                  <input
                    value={extra.description}
                    onChange={(e) =>
                      update(extra.id, { description: e.target.value })
                    }
                    className="w-full border rounded-sm px-3 py-2 bg-white"
                    style={{ borderColor: `${BRAND}26` }}
                    placeholder="Small cute ribbon..."
                  />
                </Field>

                {extra.type === "text" && (
                  <>
                    <Field label="Text title shown to user">
                      <input
                        value={extra.promptTitle || ""}
                        onChange={(e) =>
                          update(extra.id, { promptTitle: e.target.value })
                        }
                        className="w-full border rounded-sm px-3 py-2 bg-white"
                        style={{ borderColor: `${BRAND}26` }}
                        placeholder="Engraving text"
                      />
                    </Field>

                    <Field label="Text placeholder">
                      <input
                        value={extra.promptPlaceholder || ""}
                        onChange={(e) =>
                          update(extra.id, {
                            promptPlaceholder: e.target.value,
                          })
                        }
                        className="w-full border rounded-sm px-3 py-2 bg-white"
                        style={{ borderColor: `${BRAND}26` }}
                        placeholder="Type what you want..."
                      />
                    </Field>

                    <label className="flex items-center gap-2 text-sm font-semibold text-slate-700 sm:col-span-2">
                      <input
                        type="checkbox"
                        checked={!!extra.requiredText}
                        onChange={(e) =>
                          update(extra.id, { requiredText: e.target.checked })
                        }
                      />
                      Require reply before checkout
                    </label>
                  </>
                )}
              </div>

              <button
                type="button"
                onClick={() => remove(extra.id)}
                className="w-10 h-10 rounded-sm border bg-white flex items-center justify-center hover:bg-slate-50"
                style={{ borderColor: `${BRAND}26` }}
                aria-label="Remove extra"
              >
                <Trash2 className="w-4 h-4 text-rose-500" />
              </button>
            </div>

            {/* Extra variants */}
            <div
              className="rounded-md border bg-white p-4 space-y-3"
              style={{ borderColor: `${BRAND}26` }}
            >
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-semibold text-slate-900">
                    Variants for “{extra.name || "this extra"}”
                  </p>
                  <p className="text-xs text-slate-500">
                    Basic / Premium, etc.
                  </p>
                </div>

                <button
                  type="button"
                  onClick={() => addExtraVariant(extra.id)}
                  className="inline-flex items-center gap-2 text-xs font-semibold px-3 py-2 rounded-sm text-white hover:opacity-90"
                  style={{ backgroundColor: BRAND }}
                >
                  <Plus className="w-4 h-4" />
                  Add Variant
                </button>
              </div>

              {(extra.variants || []).length > 0 ? (
                <div className="space-y-2">
                  {(extra.variants || []).map((v) => (
                    <div
                      key={v.id}
                      className="border rounded-md p-3 bg-white"
                      style={{ borderColor: `${BRAND}1f` }}
                    >
                      <div className="grid sm:grid-cols-3 gap-2 items-center">
                        <input
                          value={v.name}
                          onChange={(e) =>
                            updateExtraVariant(extra.id, v.id, {
                              name: e.target.value,
                            })
                          }
                          placeholder="Variant name (e.g. Premium)"
                          className="w-full border rounded-sm px-3 py-2 bg-white"
                          style={{ borderColor: `${BRAND}26` }}
                        />
                        <input
                          type="number"
                          value={v.price}
                          onChange={(e) =>
                            updateExtraVariant(extra.id, v.id, {
                              price: e.target.value,
                            })
                          }
                          placeholder="Price"
                          className="w-full border rounded-sm px-3 py-2 bg-white"
                          style={{ borderColor: `${BRAND}26` }}
                        />
                        <div className="flex gap-2">
                          <input
                            type="number"
                            value={v.stock}
                            onChange={(e) =>
                              updateExtraVariant(extra.id, v.id, {
                                stock: e.target.value,
                              })
                            }
                            placeholder="Stock"
                            className="w-full border rounded-sm px-3 py-2 bg-white"
                            style={{ borderColor: `${BRAND}26` }}
                          />
                          <button
                            type="button"
                            onClick={() => removeExtraVariant(extra.id, v.id)}
                            className="w-10 h-10 rounded-sm border bg-white flex items-center justify-center hover:bg-slate-50"
                            style={{ borderColor: `${BRAND}26` }}
                            aria-label="Remove extra variant"
                          >
                            <Trash2 className="w-4 h-4 text-rose-500" />
                          </button>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-sm text-slate-500">
                  No variants for this extra yet.
                </p>
              )}
            </div>
          </div>
        ))}

        {value.length === 0 && (
          <div
            className="rounded-md border bg-white p-4 text-sm text-slate-600"
            style={{ borderColor: `${BRAND}26` }}
          >
            No extras yet. Click{" "}
            <span className="font-semibold">Add Extra</span>.
          </div>
        )}
      </div>
    </div>
  );
}

/** ---------- Custom fields ---------- **/
function CustomFieldsEditor({ value = [], onChange }) {
  const addField = () => {
    onChange([
      ...value,
      {
        id: uid(),
        label: "notes",
        displayTitle: "Message to recipient",
        type: "textarea",
        required: false,
        placeholder: "Write something sweet...",
      },
    ]);
  };
  const update = (id, patch) =>
    onChange(value.map((f) => (f.id === id ? { ...f, ...patch } : f)));
  const remove = (id) => onChange(value.filter((f) => f.id !== id));

  return (
    <div
      className="rounded-md border bg-white p-4 space-y-3"
      style={{ borderColor: `${BRAND}26` }}
    >
      <div className="flex items-center justify-between gap-3">
        <div>
          <p className="font-semibold text-slate-900">Custom Fields</p>
          <p className="text-xs text-slate-500">
            Personalization inputs like “Notes”.
          </p>
        </div>
        <button
          type="button"
          onClick={addField}
          className="inline-flex items-center gap-2 text-xs font-semibold px-3 py-2 rounded-sm text-white hover:opacity-90"
          style={{ backgroundColor: BRAND }}
        >
          <Plus className="w-4 h-4" />
          Add Field
        </button>
      </div>

      <div className="space-y-3">
        {value.map((field) => (
          <div
            key={field.id}
            className="border rounded-md p-3 bg-white"
            style={{ borderColor: `${BRAND}1f` }}
          >
            <div className="flex items-start justify-between gap-3">
              <div className="grid sm:grid-cols-2 gap-4 flex-1">
                <Field label="Internal key (label)">
                  <input
                    value={field.label}
                    onChange={(e) =>
                      update(field.id, { label: e.target.value })
                    }
                    className="w-full border rounded-sm px-3 py-2 bg-white"
                    style={{ borderColor: `${BRAND}26` }}
                    placeholder="notes"
                  />
                </Field>

                <Field label="Title shown to user">
                  <input
                    value={field.displayTitle || ""}
                    onChange={(e) =>
                      update(field.id, { displayTitle: e.target.value })
                    }
                    className="w-full border rounded-sm px-3 py-2 bg-white"
                    style={{ borderColor: `${BRAND}26` }}
                    placeholder="Message to recipient"
                  />
                </Field>

                <Field label="Type">
                  <select
                    value={field.type || "text"}
                    onChange={(e) => update(field.id, { type: e.target.value })}
                    className="w-full border rounded-sm px-3 py-2 bg-white"
                    style={{ borderColor: `${BRAND}26` }}
                  >
                    <option value="text">Text</option>
                    <option value="textarea">Textarea (notes)</option>
                    <option value="number">Number</option>
                    <option value="email">Email</option>
                  </select>
                </Field>

                <Field label="Placeholder">
                  <input
                    value={field.placeholder || ""}
                    onChange={(e) =>
                      update(field.id, { placeholder: e.target.value })
                    }
                    className="w-full border rounded-sm px-3 py-2 bg-white"
                    style={{ borderColor: `${BRAND}26` }}
                    placeholder="Write something sweet..."
                  />
                </Field>

                <label className="flex items-center gap-2 text-sm font-semibold text-slate-700 sm:col-span-2">
                  <input
                    type="checkbox"
                    checked={!!field.required}
                    onChange={(e) =>
                      update(field.id, { required: e.target.checked })
                    }
                  />
                  Required
                </label>
              </div>

              <button
                type="button"
                onClick={() => remove(field.id)}
                className="w-10 h-10 rounded-sm border bg-white flex items-center justify-center hover:bg-slate-50"
                style={{ borderColor: `${BRAND}26` }}
                aria-label="Remove field"
              >
                <Trash2 className="w-4 h-4 text-rose-500" />
              </button>
            </div>
          </div>
        ))}

        {value.length === 0 && (
          <div
            className="rounded-md border bg-white p-4 text-sm text-slate-600"
            style={{ borderColor: `${BRAND}26` }}
          >
            No custom fields yet. Click{" "}
            <span className="font-semibold">Add Field</span>.
          </div>
        )}
      </div>
    </div>
  );
}

export function ProductFormModal({ isOpen, onClose, product }) {
  const { addProduct, updateProduct, categories, savingProduct, getNextSku } =
    useProducts();

  const isEdit = !!product;

  const [newImages, setNewImages] = useState([]);
  const [loadingSku, setLoadingSku] = useState(false);

  const [newImagePreviews, setNewImagePreviews] = useState([]);

  const [step, setStep] = useState(0);

  const [formData, setFormData] = useState({
    sku: product?.sku ? Number(product.sku) : "",

    name: product?.name || "",
    description: product?.description || "",
    category: product?.category || "",
    price: product?.price ?? "",
    stock: product?.stock ?? 0,
    isFeatured: !!product?.isFeatured,
    existingImages: product?.images || [],
    variants: product?.variants || [],
    extras: product?.extras || [],
    customFields: product?.customFields || [],
  });

  const emptyForm = {
    sku: "",
    name: "",
    description: "",
    category: "",
    price: "",
    stock: 0,
    isFeatured: false,
    existingImages: [],
    variants: [],
    extras: [],
    customFields: [],
  };

  const steps = useMemo(
    () => [
      {
        key: "basic",
        label: "Basics",
        icon: <Sparkles className="w-4 h-4" style={{ color: BRAND }} />,
      },
      {
        key: "media",
        label: "Media",
        icon: <ImageIcon className="w-4 h-4" style={{ color: BRAND }} />,
      },
      {
        key: "extras",
        label: "Extras",
        icon: <Sparkles className="w-4 h-4" style={{ color: BRAND }} />,
      },
      {
        key: "variants",
        label: "Variants",
        icon: <Package className="w-4 h-4" style={{ color: BRAND }} />,
      },
      {
        key: "custom",
        label: "Custom",
        icon: <Sparkles className="w-4 h-4" style={{ color: BRAND }} />,
      },
      {
        key: "review",
        label: "Review",
        icon: <CheckCircle2 className="w-4 h-4" style={{ color: BRAND }} />,
      },
    ],
    [],
  );
  useEffect(() => {
    const init = async () => {
      setFormData({
        sku: product?.sku ? Number(product.sku) : "",

        name: product?.name || "",
        description: product?.description || "",
        category: product?.category || "",
        price: product?.price ?? "",
        stock: product?.stock ?? 0,
        isFeatured: !!product?.isFeatured,
        existingImages: product?.images || [],
        extras: product?.extras || [],
        variants: product?.variants || [],
        customFields: product?.customFields || [],
      });

      setStep(0);
      setNewImages([]);
      setNewImagePreviews([]);

      // ✅ NEW PRODUCT: get next numeric sku from DB
      if (!product) {
        try {
          setLoadingSku(true);
          const next = await getNextSku();
          setFormData((p) => ({ ...p, sku: next })); // next is already number
        } finally {
          setLoadingSku(false);
        }
      }
    };

    init();
  }, [product?.id, categories]); // keep your deps style

  useEffect(() => {
    if (!isOpen) return;

    setStep(0);
    setNewImages([]);
    setNewImagePreviews([]);

    if (product) {
      setFormData({
        ...emptyForm,
        sku: Number(product.sku || 0) || "",
        name: product.name || "",
        description: product.description || "",
        category: product.category || "",
        price: product.price ?? "",
        stock: product.stock ?? 0,
        isFeatured: !!product.isFeatured,
        existingImages: product.images || [],
        variants: product.variants || [],
        extras: product.extras || [],
        customFields: product.customFields || [],
      });
    } else {
      setFormData(emptyForm);
      (async () => {
        try {
          setLoadingSku(true);
          const next = await getNextSku();
          setFormData((p) => ({ ...p, sku: next }));
        } finally {
          setLoadingSku(false);
        }
      })();
    }
  }, [isOpen, product?.id, getNextSku]);

  useEffect(() => {
    return () => {
      newImagePreviews.forEach((url) => URL.revokeObjectURL(url));
    };
  }, [newImagePreviews]);

  const removeExistingImage = (url) => {
    setFormData((prev) => ({
      ...prev,
      existingImages: (prev.existingImages || []).filter((img) => img !== url),
    }));
  };

  const onPickImages = (files) => {
    const arr = Array.from(files || []);
    newImagePreviews.forEach((url) => URL.revokeObjectURL(url));

    const previews = arr.map((f) => URL.createObjectURL(f));
    setNewImages(arr);
    setNewImagePreviews(previews);
  };

  const removeNewImage = (index) => {
    setNewImages((prev) => prev.filter((_, i) => i !== index));
    setNewImagePreviews((prev) => {
      const url = prev[index];
      if (url) URL.revokeObjectURL(url);
      return prev.filter((_, i) => i !== index);
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log(Number(formData.sku));
    const payload = {
      sku: Number(formData.sku),

      name: formData.name.trim(),
      description: formData.description.trim(),
      category: formData.category,
      price: toNumber(formData.price, 0),
      isFeatured: !!formData.isFeatured,
      stock: toNumber(formData.stock, 0),
      images: formData.existingImages || [],
      variants: (formData.variants || []).map((v) => ({
        id: v.id || uid(),
        name: (v.name || "").trim(),
        price: toNumber(v.price, 0),
        stock: toNumber(v.stock, 0),
      })),
      extras: (formData.extras || []).map((x) => ({
        id: x.id || uid(),
        name: (x.name || "").trim(),
        price: toNumber(x.price, 0),
        type: x.type || "toggle",
        promptTitle: x.promptTitle || "Your text",
        promptPlaceholder: x.promptPlaceholder || "Type here...",
        requiredText: !!x.requiredText,
        description: x.description || "",

        stock: x.stock === "" || x.stock == null ? null : toNumber(x.stock, 0),
        active: x.active !== false,
        variants: (x.variants || []).map((v) => ({
          id: v.id || uid(),
          name: (v.name || "").trim(),
          price: toNumber(v.price, 0),
          stock: toNumber(v.stock, 0),
        })),
      })),
      customFields: (formData.customFields || []).map((f) => ({
        id: f.id || uid(),
        label: (f.label || "").trim(),
        displayTitle: (f.displayTitle || "").trim(),
        type: f.type || "text",
        required: !!f.required,
        placeholder: f.placeholder || "",
      })),
    };

    try {
      if (isEdit) {
        await updateProduct(product.id, payload, newImages);
      } else {
        await addProduct(payload, newImages);
      }
      onClose();
    } catch (err) {
      console.error(err);
      alert("Error saving product");
    }
  };

  const canNext = () => {
    if (step === 0)
      return !!formData.name.trim() && !!String(formData.price).trim();
    return true;
  };

  const goNext = () => setStep((s) => Math.min(s + 1, steps.length - 1));
  const goBack = () => setStep((s) => Math.max(s - 1, 0));

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent
        className="sm:max-w-3xl w-full p-0 bg-white max-h-[90vh] flex flex-col rounded-md border"
        style={{ borderColor: `${BRAND}26` }}
      >
        {/* Minimal header */}
        <div
          className="relative border-b"
          style={{ borderColor: `${BRAND}26` }}
        >
          <div className="p-6">
            <DialogHeader>
              <DialogTitle className="text-xl md:text-2xl font-semibold text-slate-900">
                {isEdit ? "Edit Product" : "Create a New Product"}
              </DialogTitle>
              <p className="text-slate-500 text-sm mt-1">
                Clean segmented flow — jump between steps anytime.
              </p>
            </DialogHeader>

            <DialogClose asChild>
              <button
                className="absolute top-5 right-5 p-2 rounded-sm border bg-white hover:bg-slate-50"
                style={{ borderColor: `${BRAND}26` }}
              >
                <X className="w-5 h-5" style={{ color: BRAND }} />
              </button>
            </DialogClose>
          </div>
        </div>

        <form
          onSubmit={handleSubmit}
          className="p-6 space-y-4 flex-1 overflow-y-auto overscroll-contain"
        >
          <SegmentedSteps steps={steps} current={step} onGo={setStep} />

          {/* Body */}
          <div
            className="rounded-md border bg-white p-4 min-h-[300px]"
            style={{ borderColor: `${BRAND}26` }}
          >
            {step === 0 && (
              <div className="grid md:grid-cols-2 gap-4">
                <div
                  className="rounded-md border bg-white p-4 space-y-4"
                  style={{ borderColor: `${BRAND}26` }}
                >
                  <Field label="SKU (auto)" hint="Generated automatically">
                    <input
                      value={loadingSku ? "..." : formData.sku}
                      readOnly
                      className="w-full border rounded-sm px-3 py-2 bg-slate-50 cursor-not-allowed"
                      style={{ borderColor: `${BRAND}26` }}
                    />
                  </Field>

                  <Field label="Product name">
                    <input
                      value={formData.name}
                      onChange={(e) =>
                        setFormData((p) => ({ ...p, name: e.target.value }))
                      }
                      className="w-full border rounded-sm px-3 py-2 bg-white"
                      style={{ borderColor: `${BRAND}26` }}
                      placeholder="Gold Cartel Jewelry"
                      required
                    />
                  </Field>

                  <Field label="Category">
                    <select
                      value={formData.category}
                      onChange={(e) =>
                        setFormData((p) => ({ ...p, category: e.target.value }))
                      }
                      className="w-full border rounded-sm px-3 py-2 bg-white"
                      style={{ borderColor: `${BRAND}26` }}
                    >
                      {categories.map((c) => (
                        <option key={c} value={c}>
                          {c}
                        </option>
                      ))}
                    </select>
                  </Field>

                  <label className="flex items-center gap-3 text-sm font-semibold text-slate-800">
                    <input
                      type="checkbox"
                      checked={!!formData.isFeatured}
                      onChange={(e) =>
                        setFormData((p) => ({
                          ...p,
                          isFeatured: e.target.checked,
                        }))
                      }
                      className="h-4 w-4"
                    />
                    Mark as Featured
                  </label>
                </div>

                <div
                  className="rounded-md border bg-white p-4 space-y-4"
                  style={{ borderColor: `${BRAND}26` }}
                >
                  <Field label="Base price (NGN)">
                    <input
                      type="number"
                      value={formData.price}
                      onChange={(e) =>
                        setFormData((p) => ({ ...p, price: e.target.value }))
                      }
                      className="w-full border rounded-sm px-3 py-2 bg-white"
                      style={{ borderColor: `${BRAND}26` }}
                      placeholder="3000"
                      required
                    />
                  </Field>

                  <Field label="Stock">
                    <input
                      type="number"
                      value={formData.stock}
                      onChange={(e) =>
                        setFormData((p) => ({ ...p, stock: e.target.value }))
                      }
                      className="w-full border rounded-sm px-3 py-2 bg-white"
                      style={{ borderColor: `${BRAND}26` }}
                      placeholder="30"
                      required
                    />
                  </Field>

                  <Field label="Description" hint="Short + clear sells better">
                    <textarea
                      value={formData.description}
                      onChange={(e) =>
                        setFormData((p) => ({
                          ...p,
                          description: e.target.value,
                        }))
                      }
                      className="w-full border rounded-sm px-3 py-2 bg-white"
                      style={{ borderColor: `${BRAND}26` }}
                      rows={5}
                      placeholder="This allows you purchase useful items..."
                      required
                    />
                  </Field>
                </div>
              </div>
            )}

            {step === 1 && (
              <div className="grid lg:grid-cols-2 gap-4">
                <div
                  className="rounded-md border bg-white p-4 space-y-3"
                  style={{ borderColor: `${BRAND}26` }}
                >
                  <p className="font-semibold text-slate-900">Current Images</p>

                  {(formData.existingImages || []).length > 0 ? (
                    <div className="flex gap-2 overflow-x-auto pb-2">
                      {formData.existingImages.map((url) => (
                        <div
                          key={url}
                          className="relative w-24 h-24 rounded-sm overflow-hidden border"
                          style={{ borderColor: `${BRAND}26` }}
                        >
                          <img
                            src={url}
                            alt="Existing"
                            className="w-full h-full object-cover"
                          />
                          <button
                            type="button"
                            onClick={() => removeExistingImage(url)}
                            className="absolute top-2 right-2 w-8 h-8 rounded-sm bg-white/90 border flex items-center justify-center hover:bg-white"
                            style={{ borderColor: `${BRAND}26` }}
                            title="Remove existing image"
                          >
                            <X className="w-4 h-4 text-slate-800" />
                          </button>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <p className="text-sm text-slate-500">
                      No existing images.
                    </p>
                  )}

                  <p className="text-xs text-slate-500">
                    Removing here deletes it from the product record.
                  </p>
                </div>

                <div
                  className="rounded-md border bg-white p-4 space-y-3"
                  style={{ borderColor: `${BRAND}26` }}
                >
                  <p className="font-semibold text-slate-900">
                    Upload New Images
                  </p>

                  <input
                    type="file"
                    multiple
                    onChange={(e) => onPickImages(e.target.files)}
                    className="w-full"
                  />

                  {newImagePreviews.length > 0 ? (
                    <div className="space-y-2">
                      <p className="text-sm font-semibold text-slate-700">
                        New previews
                      </p>
                      <div className="flex gap-2 overflow-x-auto pb-2">
                        {newImagePreviews.map((url, idx) => (
                          <div
                            key={url}
                            className="relative w-24 h-24 rounded-sm overflow-hidden border"
                            style={{ borderColor: `${BRAND}26` }}
                          >
                            <img
                              src={url}
                              alt="Preview"
                              className="w-full h-full object-cover"
                            />
                            <button
                              type="button"
                              onClick={() => removeNewImage(idx)}
                              className="absolute top-2 right-2 w-8 h-8 rounded-sm bg-white/90 border flex items-center justify-center hover:bg-white"
                              style={{ borderColor: `${BRAND}26` }}
                              title="Remove new image"
                            >
                              <X className="w-4 h-4 text-slate-800" />
                            </button>
                          </div>
                        ))}
                      </div>
                    </div>
                  ) : (
                    <p className="text-sm text-slate-500">
                      Pick images to preview them here.
                    </p>
                  )}
                </div>
              </div>
            )}

            {step === 2 && (
              <ExtrasEditor
                value={formData.extras}
                variants={formData.variants}
                onChange={(v) => setFormData((p) => ({ ...p, extras: v }))}
              />
            )}

            {step === 3 && (
              <VariantsEditor
                value={formData.variants}
                onChange={(v) => setFormData((p) => ({ ...p, variants: v }))}
              />
            )}

            {step === 4 && (
              <CustomFieldsEditor
                value={formData.customFields}
                onChange={(v) =>
                  setFormData((p) => ({ ...p, customFields: v }))
                }
              />
            )}

            {step === 5 && (
              <div className="grid md:grid-cols-2 gap-4">
                <div
                  className="rounded-md border bg-white p-4 space-y-2"
                  style={{ borderColor: `${BRAND}26` }}
                >
                  <p className="font-semibold text-slate-900">Summary</p>
                  <div className="text-sm text-slate-700 space-y-1">
                    <p>
                      <span className="font-semibold">SKU:</span> {formData.sku}
                    </p>
                    <p>
                      <span className="font-semibold">Name:</span>{" "}
                      {formData.name}
                    </p>
                    <p>
                      <span className="font-semibold">Category:</span>{" "}
                      {formData.category}
                    </p>
                    <p>
                      <span className="font-semibold">Price:</span>{" "}
                      {toNumber(formData.price, 0)}
                    </p>
                    <p>
                      <span className="font-semibold">Stock:</span>{" "}
                      {toNumber(formData.stock, 0)}
                    </p>
                    <p>
                      <span className="font-semibold">Images:</span>{" "}
                      {(formData.existingImages?.length || 0) +
                        (newImages?.length || 0)}
                    </p>
                    <p>
                      <span className="font-semibold">Variants:</span>{" "}
                      {formData.variants?.length || 0}
                    </p>
                    <p>
                      <span className="font-semibold">Extras:</span>{" "}
                      {formData.extras?.length || 0}
                    </p>
                    <p>
                      <span className="font-semibold">Custom fields:</span>{" "}
                      {formData.customFields?.length || 0}
                    </p>
                  </div>
                </div>

                <div
                  className="rounded-md border bg-white p-4"
                  style={{ borderColor: `${BRAND}26` }}
                >
                  <p className="font-semibold text-slate-900">Ready?</p>
                  <p className="text-sm text-slate-600 mt-1">
                    This will save the product and upload new images.
                  </p>

                  <button
                    type="submit"
                    disabled={savingProduct}
                    className="mt-4 w-full h-12 rounded-sm font-semibold text-white transition hover:opacity-90 disabled:opacity-60"
                    style={{
                      backgroundColor: savingProduct ? "#94a3b8" : BRAND,
                    }}
                  >
                    {savingProduct
                      ? "Saving..."
                      : isEdit
                        ? "Update Product"
                        : "Create Product"}
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* Footer controls */}
          <div className="flex items-center justify-between gap-3">
            <button
              type="button"
              onClick={() => setStep((s) => Math.max(s - 1, 0))}
              disabled={step === 0}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-sm border bg-white hover:bg-slate-50 disabled:opacity-50"
              style={{ borderColor: `${BRAND}26` }}
            >
              <ChevronLeft className="w-4 h-4" style={{ color: BRAND }} />
              Back
            </button>

            {step < steps.length - 1 ? (
              <button
                type="button"
                onClick={() =>
                  setStep((s) => Math.min(s + 1, steps.length - 1))
                }
                disabled={!canNext()}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-sm text-white font-semibold hover:opacity-90 disabled:opacity-50"
                style={{ backgroundColor: BRAND }}
              >
                Next
                <ChevronRight className="w-4 h-4" />
              </button>
            ) : null}
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}
